name: Build Docker Image and Push to Dockerhub

on:
  push:
    branches: [ main ]
    paths:
      - html/**
      - pdf/**
      - src/**
      - dockerignore
      - .python-version
      - Dockerfile
      - pyproject.toml
      - uv.lock

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/deepauto-intern-assignment:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/deepauto-intern-assignment:${{ github.sha }}